### ISSUE TITLE
args not being recognized

### ISSUE THREAD

**Issue by panamantis** [hugovk/satellite-pies#1]
Great program!  But, it's currently not accepting my command parameters per your examples.  Just defaults to the default parameters.
Looks like I have to run it via python to have it recognize arguments
`python satellite-pies -t osm`

**Comment by hugovk** [comment]
Thanks! That's strange about the parameters, it works for me with ActivePython 2.7 on Windows XP, Vista and 7. I guess it's some environment thing. But at least it's working using the `python` command. Perhaps I should update the examples to include it, that way it should always work.
